// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetYugabytedbNodeCloud("yugabytedb.node.cloud-val")
			rb.SetYugabytedbNodeHost("yugabytedb.node.host-val")
			rb.SetYugabytedbNodeRegion("yugabytedb.node.region-val")
			rb.SetYugabytedbNodeZone("yugabytedb.node.zone-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 4, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 4, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("yugabytedb.node.cloud")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "yugabytedb.node.cloud-val", val.Str())
			}
			val, ok = res.Attributes().Get("yugabytedb.node.host")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "yugabytedb.node.host-val", val.Str())
			}
			val, ok = res.Attributes().Get("yugabytedb.node.region")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "yugabytedb.node.region-val", val.Str())
			}
			val, ok = res.Attributes().Get("yugabytedb.node.zone")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "yugabytedb.node.zone-val", val.Str())
			}
		})
	}
}
