// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetYugabytedbNodeCloud sets provided value as "yugabytedb.node.cloud" attribute.
func (rb *ResourceBuilder) SetYugabytedbNodeCloud(val string) {
	if rb.config.YugabytedbNodeCloud.Enabled {
		rb.res.Attributes().PutStr("yugabytedb.node.cloud", val)
	}
}

// SetYugabytedbNodeHost sets provided value as "yugabytedb.node.host" attribute.
func (rb *ResourceBuilder) SetYugabytedbNodeHost(val string) {
	if rb.config.YugabytedbNodeHost.Enabled {
		rb.res.Attributes().PutStr("yugabytedb.node.host", val)
	}
}

// SetYugabytedbNodeRegion sets provided value as "yugabytedb.node.region" attribute.
func (rb *ResourceBuilder) SetYugabytedbNodeRegion(val string) {
	if rb.config.YugabytedbNodeRegion.Enabled {
		rb.res.Attributes().PutStr("yugabytedb.node.region", val)
	}
}

// SetYugabytedbNodeZone sets provided value as "yugabytedb.node.zone" attribute.
func (rb *ResourceBuilder) SetYugabytedbNodeZone(val string) {
	if rb.config.YugabytedbNodeZone.Enabled {
		rb.res.Attributes().PutStr("yugabytedb.node.zone", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
